### PR TITLE
use gem helper from celluloid/culture to manage x-celluloid dependencies

### PR DESCRIPTION
**Pull request by niamster**
use w/a for celluloid/culture#6

### CODE REVIEW

**Comment by niamster** [comment]
Not for merge before celluloid/culture#11 is actually merged. Need to update GIT submodule first.
This is just for RFC.

**Comment by niamster** [comment]
cc @digitalextremist

**Comment by digitalextremist** [comment]
Awesome, thanks for the demonstration. I'm going to merge this, adapt it a bit and apply it to the rest of the gems. Mainly, I think the `.celluloid.yml` ought to be in `culture/` itself, otherwise we have a ton of files to update again. Also, just so you know, in `Gemfile` everything needs to come in after the `gemspec` call, otherwise your local repository overrides will not be used. For example, each of these packages I map to the ones on my own system, but if bundler loads those gems before `gemspec` it uses cut gems.

**Comment by niamster** [comment]
@digitalextremist it's weird that everything has to go after `gemspec`. I did test and in both cases bundler applied specs from Gemfile

**Comment by digitalextremist** [comment]
I can't remember where I read this, but @wycats wrote about this somewhere... ultimately the #6 problem was worked around by putting the gems underneath `gemspec` so local paths could be used by bundler

**Comment by digitalextremist** [comment]
Ah, here it was: http://yehudakatz.com/2010/12/16/clarifying-the-roles-of-the-gemspec-and-gemfile/

Under `Gem Development`

**Pull request merged**
